### ISSUE TITLE
CIの設定

### ISSUE THREAD

**Issue by Asapi1020** [WFrog2511/game-center#6]
Pushの度にGitHub上でもLinux環境を仮想して、テストが通ることを継続的にチェックする

**Comment by WFrog2511** [comment]
Pushのたびにテストのために仮想環境を動かすと、課金が発生しないかと思いました。
しかし、無料アカウントでも月 2000分は無料([参考](https://docs.github.com/ja/billing/managing-billing-for-github-actions/about-billing-for-github-actions)) であり、仮にテスト処理に10分かかるとしても、月に200回はPushできることになるため問題無いと判断しました。

**Comment by WFrog2511** [comment]
再度、確認して認識が誤っていたことが分かりました。
これはプライベートリポジトリの場合であり、パブリックリポジトリは無料枠を無制限に使える ということであり、なおさらGitHub Actionsを使って問題無いと判断しました。
